# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/gpu-sprint',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/gpu-sprint',
                'lib_path': 'gpu_sprint'},
  'syms': { 'gpu_sprint.benchmark': {'gpu_sprint.benchmark.benchmark': ('benchmark.html#benchmark', 'gpu_sprint/benchmark.py')},
            'gpu_sprint.cli': {'gpu_sprint.cli.cli': ('cli.html#cli', 'gpu_sprint/cli.py')}}}