# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/gpu-sprint',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/gpu-sprint',
                'lib_path': 'gpu_sprint'},
  'syms': {'gpu_sprint.core': {'gpu_sprint.core.foo': ('core.html#foo', 'gpu_sprint/core.py')}}}